FROM java:8
EXPOSE 8080
ADD /target/roadmapSpringBootExercise-0.0.1-SNAPSHOT.jar  roadmapSpringBootExercise-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "roadmapSpringBootExercise-0.0.1-SNAPSHOT.jar"] 